name: Build Qt Project

on:
  push:
    branches:
      - main
      - Test
  pull_request:
    branches:
      - main
      - Test

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: Test

    - name: Setup Visual Studio 2022
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Set up Qt environment variables
      run: |
        echo "QTDIR=C:\\Qt\\6.2.4\\msvc2019_64" >> $GITHUB_ENV
        echo "QtMsBuild=${{ github.workspace }}\\QtMsBuild" >> $GITHUB_ENV
        echo "DefaultQtVersion=C:\\Qt\\6.2.4\\msvc2019_64" >> $GITHUB_ENV
        echo "PATH=${{ env.PATH }};C:\\Qt\\6.2.4\\msvc2019_64\\bin" >> $GITHUB_ENV

    - name: Import Qt version registry settings
      run: reg import "${{ github.workspace }}\\QT_Version.reg"

    - name: Verify Qt setup
      env:
        QTDIR: ${{ env.QTDIR }}
        QtMsBuild: ${{ env.QtMsBuild }}
        DefaultQtVersion: ${{ env.DefaultQtVersion }}
      run: |
        echo "QTDIR=$QTDIR"
        echo "QtMsBuild=$QtMsBuild"
        echo "DefaultQtVersion=$DefaultQtVersion"
        if (-not (Test-Path "$QTDIR\\bin\\qmake.exe")) {
          throw "qmake.exe not found in $QTDIR\\bin"
        }
        & "$QTDIR\\bin\\qmake.exe" -v

    - name: Build the project using msbuild
      env:
        QTDIR: ${{ env.QTDIR }}
        QtMsBuild: ${{ env.QtMsBuild }}
        DefaultQtVersion: ${{ env.DefaultQtVersion }}
        PATH: ${{ env.PATH }}
      run: |
        msbuild /p:Configuration=Release /p:Platform=x64 ${{ github.workspace }}\path\to\your\solution.sln
