name: Build Qt Project

on:
  push:
    branches:
      - Test
  pull_request:
    branches:
      - Test

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: Test

    - name: Setup Visual Studio 2022
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Set up Qt environment variables
      run: |
        $qtPath = "C:\\Qt\\6.2.4\\msvc2019_64"
        [Environment]::SetEnvironmentVariable("QTDIR", $qtPath, "Machine")
        [Environment]::SetEnvironmentVariable("PATH", $env:PATH + ";$qtPath\\bin", "Machine")

    - name: Copy QtMsBuild directory
      run: |
        Copy-Item -Recurse -Force "${{ github.workspace }}\QtMsBuild" "$env:LOCALAPPDATA\QtMsBuild"

    - name: Set QtMsBuild environment variable
      run: |
        [Environment]::SetEnvironmentVariable("QtMsBuild", "$env:LOCALAPPDATA\QtMsBuild", "Machine")

    - name: Set DefaultQtVersion environment variable
      run: |
        [Environment]::SetEnvironmentVariable("DefaultQtVersion", "C:\\Qt\\6.2.4\\msvc2019_64", "Machine")

    - name: Import Qt version registry settings
      run: reg import "${{ github.workspace }}\QT_Version.reg"

    - name: Build the project using msbuild
      run: |
        msbuild /p:Configuration=Release /p:Platform=x64 path\to\your\solution.sln
